openapi: 3.0.1
info:
  title: CRUD Demo
  description: CRUD Demo
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Generated server url

paths:
  /users/{userId}:
    $ref: "./api/paths/users.yaml"
components:
  schemas:
    UserApi:
      $ref: "./api/components/User.yaml"
    RegisterUserApi:
      $ref: "./api/components/RegisterUser.yaml"
    AddressApi:
      $ref: "./api/components/Address.yaml"
    BusinessApi:
      $ref: "./api/components/BusinessApi.yaml"
    QuizApi:
      $ref: "./api/components/QuizApi.yaml"