openapi: 3.0.1
info:
  title: CRUD Demo
  description: CRUD Demo
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Generated server url

paths:
  /users/{userId}:
    $ref: "./api/paths/users.yaml"
components:
  schemas:
    UserApi:
      $ref: "./api/components/UserApi.yaml"
    RegisterUserApi:
      $ref: "./api/components/RegisterUserApi.yaml"
    AddressApi:
      $ref: "./api/components/AddressApi.yaml"
    BusinessApi:
      $ref: "./api/components/BusinessApi.yaml"
    QuizApi:
      $ref: "./api/components/QuizApi.yaml"
    NutritionApi:
      $ref: "./api/components/NutritionApi.yaml"
    IngredientApi:
      $ref: "./api/components/IngredientApi.yaml"
    MealApi:
      $ref: "./api/components/MealApi.yaml"